# Profiles for Volatility 2.5 Insert Statements
insert into profiles values ('VistaSP0x64','A Profile for Windows Vista SP0 x64','2.5');
insert into profiles values ('VistaSP0x86','A Profile for Windows Vista SP0 x86','2.5');
insert into profiles values ('VistaSP1x64','A Profile for Windows Vista SP1 x64','2.5');
insert into profiles values ('VistaSP1x86','A Profile for Windows Vista SP1 x86','2.5');
insert into profiles values ('VistaSP2x64','A Profile for Windows Vista SP2 x64','2.5');
insert into profiles values ('VistaSP2x86','A Profile for Windows Vista SP2 x86','2.5');
insert into profiles values ('Win10x64','A Profile for Windows 10 x64','2.5');
insert into profiles values ('Win10x86','A Profile for Windows 10 x86','2.5');
insert into profiles values ('Win2003SP0x86','A Profile for Windows 2003 SP0 x86','2.5');
insert into profiles values ('Win2003SP1x64','A Profile for Windows 2003 SP1 x64','2.5');
insert into profiles values ('Win2003SP1x86','A Profile for Windows 2003 SP1 x86','2.5');
insert into profiles values ('Win2003SP2x64','A Profile for Windows 2003 SP2 x64','2.5');
insert into profiles values ('Win2003SP2x86','A Profile for Windows 2003 SP2 x86','2.5');
insert into profiles values ('Win2008R2SP0x64','A Profile for Windows 2008 R2 SP0 x64','2.5');
insert into profiles values ('Win2008R2SP1x64','A Profile for Windows 2008 R2 SP1 x64','2.5');
insert into profiles values ('Win2008SP1x64','A Profile for Windows 2008 SP1 x64','2.5');
insert into profiles values ('Win2008SP1x86','A Profile for Windows 2008 SP1 x86','2.5');
insert into profiles values ('Win2008SP2x64','A Profile for Windows 2008 SP2 x64','2.5');
insert into profiles values ('Win2008SP2x86','A Profile for Windows 2008 SP2 x86','2.5');
insert into profiles values ('Win2012R2x64','A Profile for Windows Server 2012 R2 x64','2.5');
insert into profiles values ('Win2012x64','A Profile for Windows Server 2012 x64','2.5');
insert into profiles values ('Win7SP0x64','A Profile for Windows 7 SP0 x64','2.5');
insert into profiles values ('Win7SP0x86','A Profile for Windows 7 SP0 x86','2.5');
insert into profiles values ('Win7SP1x64','A Profile for Windows 7 SP1 x64','2.5');
insert into profiles values ('Win7SP1x86','A Profile for Windows 7 SP1 x86','2.5');
insert into profiles values ('Win81U1x64','A Profile for Windows 8.1 Update 1 x64','2.5');
insert into profiles values ('Win81U1x86','A Profile for Windows 8.1 Update 1 x86','2.5');
insert into profiles values ('Win8SP0x64','A Profile for Windows 8 x64','2.5');
insert into profiles values ('Win8SP0x86','A Profile for Windows 8 x86','2.5');
insert into profiles values ('Win8SP1x64','A Profile for Windows 8.1 x64','2.5');
insert into profiles values ('Win8SP1x86','A Profile for Windows 8.1 x86','2.5');
insert into profiles values ('WinXPSP1x64','A Profile for Windows XP SP1 x64','2.5');
insert into profiles values ('WinXPSP2x64','A Profile for Windows XP SP2 x64','2.5');
insert into profiles values ('WinXPSP2x86','A Profile for Windows XP SP2 x86','2.5');
insert into profiles values ('WinXPSP3x86','A Profile for Windows XP SP3 x86','2.5');

# Plugins for Volatility 2.5 Insert Statements
Insert into plugins values ('amcache','Print AmCache information','2.5');
Insert into plugins values ('apihooks','Detect API hooks in process and kernel memory','2.5');
Insert into plugins values ('atoms','Print session and window station atom tables','2.5');
Insert into plugins values ('atomscan','Pool scanner for atom tables','2.5');
Insert into plugins values ('auditpol','Prints out the Audit Policies from HKLM\SECURITY\Policy\PolAdtEv','2.5');
Insert into plugins values ('bigpools','Dump the big page pools using BigPagePoolScanner','2.5');
Insert into plugins values ('bioskbd','Reads the keyboard buffer from Real Mode memory','2.5');
Insert into plugins values ('cachedump','Dumps cached domain hashes from memory','2.5');
Insert into plugins values ('callbacks','Print system-wide notification routines','2.5');
Insert into plugins values ('clipboard','Extract the contents of the windows clipboard','2.5');
Insert into plugins values ('cmdline','Display process command-line arguments','2.5');
Insert into plugins values ('cmdscan','Extract command history by scanning for _COMMAND_HISTORY','2.5');
Insert into plugins values ('connections','Print list of open connections [Windows XP and 2003 Only]','2.5');
Insert into plugins values ('connscan','Pool scanner for tcp connections','2.5');
Insert into plugins values ('consoles','Extract command history by scanning for _CONSOLE_INFORMATION','2.5');
Insert into plugins values ('crashinfo','Dump crash-dump information','2.5');
Insert into plugins values ('deskscan','Poolscaner for tagDESKTOP (desktops)','2.5');
Insert into plugins values ('devicetree','Show device tree','2.5');
Insert into plugins values ('dlldump','Dump DLLs from a process address space','2.5');
Insert into plugins values ('dlllist','Print list of loaded dlls for each process','2.5');
Insert into plugins values ('driverirp','Driver IRP hook detection','2.5');
Insert into plugins values ('drivermodule','Associate driver objects to kernel modules','2.5');
Insert into plugins values ('driverscan','Pool scanner for driver objects','2.5');
Insert into plugins values ('dumpcerts','Dump RSA private and public SSL keys','2.5');
Insert into plugins values ('dumpfiles','Extract memory mapped and cached files','2.5');
Insert into plugins values ('dumpregistry','Dumps registry files out to disk','2.5');
Insert into plugins values ('editbox','Dumps various data from ComCtl Edit controls (experimental: ListBox, ComboBox)','2.5');
Insert into plugins values ('envars','Display process environment variables','2.5');
Insert into plugins values ('eventhooks','Print details on windows event hooks','2.5');
Insert into plugins values ('evtlogs','Extract Windows Event Logs (XP/2003 only)','2.5');
Insert into plugins values ('filescan','Pool scanner for file objects','2.5');
Insert into plugins values ('gahti','Dump the USER handle type information','2.5');
Insert into plugins values ('gditimers','Print installed GDI timers and callbacks','2.5');
Insert into plugins values ('gdt','Display Global Descriptor Table','2.5');
Insert into plugins values ('getservicesids','Get the names of services in the Registry and return Calculated SID','2.5');
Insert into plugins values ('getsids','Print the SIDs owning each process','2.5');
Insert into plugins values ('handles','Print list of open handles for each process','2.5');
Insert into plugins values ('hashdump','Dumps passwords hashes (LM/NTLM) from memory','2.5');
Insert into plugins values ('hibinfo','Dump hibernation file information','2.5');
Insert into plugins values ('hivedump','Prints out a hive','2.5');
Insert into plugins values ('hivelist','Print list of registry hives.','2.5');
Insert into plugins values ('hivescan','Pool scanner for registry hives','2.5');
Insert into plugins values ('hpakextract','Extract physical memory from an HPAK file','2.5');
Insert into plugins values ('hpakinfo','Info on an HPAK file','2.5');
Insert into plugins values ('idt','Display Interrupt Descriptor Table','2.5');
Insert into plugins values ('iehistory','Reconstruct Internet Explorer cache / history','2.5');
Insert into plugins values ('imagecopy','Copies a physical address space out as a raw DD image','2.5');
Insert into plugins values ('imageinfo','Identify information for the image','2.5');
Insert into plugins values ('impscan','Scan for calls to imported functions','2.5');
Insert into plugins values ('joblinks','Print process job link information','2.5');
Insert into plugins values ('kdbgscan','Search for and dump potential KDBG values','2.5');
Insert into plugins values ('kpcrscan','Search for and dump potential KPCR values','2.5');
Insert into plugins values ('ldrmodules','Detect unlinked DLLs','2.5');
Insert into plugins values ('limeinfo','Dump Lime file format information','2.5');
Insert into plugins values ('linux_apihooks','Checks for userland apihooks','2.5');
Insert into plugins values ('linux_arp','Print the ARP table','2.5');
Insert into plugins values ('linux_banner','Prints the Linux banner information','2.5');
Insert into plugins values ('linux_bash','Recover bash history from bash process memory','2.5');
Insert into plugins values ('linux_bash_env',"Recover a process' dynamic environment variables",'2.5');
Insert into plugins values ('linux_bash_hash','Recover bash hash table from bash process memory','2.5');
Insert into plugins values ('linux_check_afinfo','Verifies the operation function pointers of network protocols','2.5');
Insert into plugins values ('linux_check_creds','Checks if any processes are sharing credential structures','2.5');
Insert into plugins values ('linux_check_evt_arm','Checks the Exception Vector Table to look for syscall table hooking','2.5');
Insert into plugins values ('linux_check_fop','Check file operation structures for rootkit modifications','2.5');
Insert into plugins values ('linux_check_idt','Checks if the IDT has been altered','2.5');
Insert into plugins values ('linux_check_inline_kernel','Check for inline kernel hooks','2.5');
Insert into plugins values ('linux_check_modules','Compares module list to sysfs info, if available','2.5');
Insert into plugins values ('linux_check_syscall','Checks if the system call table has been altered','2.5');
Insert into plugins values ('linux_check_syscall_arm','Checks if the system call table has been altered','2.5');
Insert into plugins values ('linux_check_tty','Checks tty devices for hooks','2.5');
Insert into plugins values ('linux_cpuinfo','Prints info about each active processor','2.5');
Insert into plugins values ('linux_dentry_cache','Gather files from the dentry cache','2.5');
Insert into plugins values ('linux_dmesg','Gather dmesg buffer','2.5');
Insert into plugins values ('linux_dump_map','Writes selected memory mappings to disk','2.5');
Insert into plugins values ('linux_dynamic_env ',"Recover a process' dynamic environment variables",'2.5');
Insert into plugins values ('linux_elfs','Find ELF binaries in process mappings','2.5');
Insert into plugins values ('linux_enumerate_files','Lists files referenced by the filesystem cache','2.5');
Insert into plugins values ('linux_find_file','Lists and recovers files from memory','2.5');
Insert into plugins values ('linux_getcwd','Lists current working directory of each process','2.5');
Insert into plugins values ('linux_hidden_modules','Carves memory to find hidden kernel modules','2.5');
Insert into plugins values ('linux_ifconfig','Gathers active interfaces','2.5');
Insert into plugins values ('linux_info_regs',"It's like 'info registers' in GDB. It prints out all the",'2.5');
Insert into plugins values ('linux_iomem','Provides output similar to /proc/iomem','2.5');
Insert into plugins values ('linux_kernel_opened_files','Lists files that are opened from within the kernel','2.5');
Insert into plugins values ('linux_keyboard_notifiers','Parses the keyboard notifier call chain','2.5');
Insert into plugins values ('linux_ldrmodules','Compares the output of proc maps with the list of libraries from libdl','2.5');
Insert into plugins values ('linux_library_list','Lists libraries loaded into a process','2.5');
Insert into plugins values ('linux_librarydump','Dumps shared libraries in process memory to disk','2.5');
Insert into plugins values ('linux_list_raw','List applications with promiscuous sockets','2.5');
Insert into plugins values ('linux_lsmod','Gather loaded kernel modules','2.5');
Insert into plugins values ('linux_lsof','Lists file descriptors and their path','2.5');
Insert into plugins values ('linux_malfind','Looks for suspicious process mappings','2.5');
Insert into plugins values ('linux_memmap','Dumps the memory map for linux tasks','2.5');
Insert into plugins values ('linux_moddump','Extract loaded kernel modules','2.5');
Insert into plugins values ('linux_mount','Gather mounted fs/devices','2.5');
Insert into plugins values ('linux_mount_cache','Gather mounted fs/devices from kmem_cache','2.5');
Insert into plugins values ('linux_netfilter','Lists Netfilter hooks','2.5');
Insert into plugins values ('linux_netscan','Carves for network connection structures','2.5');
Insert into plugins values ('linux_netstat','Lists open sockets','2.5');
Insert into plugins values ('linux_pidhashtable','Enumerates processes through the PID hash table','2.5');
Insert into plugins values ('linux_pkt_queues','Writes per-process packet queues out to disk','2.5');
Insert into plugins values ('linux_plthook',"Scan ELF binaries' PLT for hooks to non-NEEDED images",'2.5');
Insert into plugins values ('linux_proc_maps','Gathers process memory maps','2.5');
Insert into plugins values ('linux_proc_maps_rb','Gathers process maps for linux through the mappings red-black tree','2.5');
Insert into plugins values ('linux_procdump',"Dumps a process's executable image to disk",'2.5');
Insert into plugins values ('linux_process_hollow','Checks for signs of process hollowing','2.5');
Insert into plugins values ('linux_psaux','Gathers processes along with full command line and start time','2.5');
Insert into plugins values ('linux_psenv','Gathers processes along with their static environment variables','2.5');
Insert into plugins values ('linux_pslist','Gather active tasks by walking the task_struct->task list','2.5');
Insert into plugins values ('linux_pslist_cache','Gather tasks from the kmem_cache','2.5');
Insert into plugins values ('linux_pstree','Shows the parent/child relationship between processes','2.5');
Insert into plugins values ('linux_psxview ','Find hidden processes with various process listings','2.5');
Insert into plugins values ('linux_recover_filesystem','Recovers the entire cached file system from memory','2.5');
Insert into plugins values ('linux_route_cache','Recovers the routing cache from memory','2.5');
Insert into plugins values ('linux_sk_buff_cache','Recovers packets from the sk_buff kmem_cache','2.5');
Insert into plugins values ('linux_slabinfo','Mimics /proc/slabinfo on a running machine','2.5');
Insert into plugins values ('linux_strings','Match physical offsets to virtual addresses (may take a while, VERY verbose)','2.5');
Insert into plugins values ('linux_threads','Prints threads of processes','2.5');
Insert into plugins values ('linux_tmpfs','Recovers tmpfs filesystems from memory','2.5');
Insert into plugins values ('linux_truecrypt_passphrase','Recovers cached Truecrypt passphrases','2.5');
Insert into plugins values ('linux_vma_cache','Gather VMAs from the vm_area_struct cache','2.5');
Insert into plugins values ('linux_volshell','Shell in the memory image','2.5');
Insert into plugins values ('linux_yarascan','A shell in the Linux memory image','2.5');
Insert into plugins values ('lsadump','Dump (decrypted) LSA secrets from the registry','2.5');
Insert into plugins values ('mac_adium','Lists Adium messages','2.5');
Insert into plugins values ('mac_apihooks','Checks for API hooks in processes','2.5');
Insert into plugins values ('mac_apihooks_kernel','Checks to see if system call and kernel functions are hooked','2.5');
Insert into plugins values ('mac_arp','Prints the arp table','2.5');
Insert into plugins values ('mac_bash','Recover bash history from bash process memory','2.5');
Insert into plugins values ('mac_bash_env',"Recover bash's environment variables",'2.5');
Insert into plugins values ('mac_bash_hash','Recover bash hash table from bash process memory','2.5');
Insert into plugins values ('mac_calendar','Gets calendar events from Calendar.app','2.5');
Insert into plugins values ('mac_check_mig_table',"Lists entires in the kernel's MIG table",'2.5');
Insert into plugins values ('mac_check_syscall_shadow','Looks for shadow system call tables','2.5');
Insert into plugins values ('mac_check_syscalls','Checks to see if system call table entries are hooked','2.5');
Insert into plugins values ('mac_check_sysctl','Checks for unknown sysctl handlers','2.5');
Insert into plugins values ('mac_check_trap_table','Checks to see if mach trap table entries are hooked','2.5');
Insert into plugins values ('mac_compressed_swap','Prints Mac OS X VM compressor stats and dumps all compressed pages','2.5');
Insert into plugins values ('mac_contacts','Gets contact names from Contacts.app','2.5');
Insert into plugins values ('mac_dead_procs','Prints terminated/de-allocated processes','2.5');
Insert into plugins values ('mac_dead_sockets','Prints terminated/de-allocated network sockets','2.5');
Insert into plugins values ('mac_dead_vnodes','Lists freed vnode structures','2.5');
Insert into plugins values ('mac_dmesg','Prints the kernel debug buffer','2.5');
Insert into plugins values ('mac_dump_file','Dumps a specified file','2.5');
Insert into plugins values ('mac_dump_maps','Dumps memory ranges of process(es), optionally including pages in compressed swap','2.5');
Insert into plugins values ('mac_dyld_maps','Gets memory maps of processes from dyld data structures','2.5');
Insert into plugins values ('mac_find_aslr_shift','Find the ASLR shift value for 10.8+ images','2.5');
Insert into plugins values ('mac_get_profile','Automatically detect Mac profiles','2.5');
Insert into plugins values ('mac_ifconfig','Lists network interface information for all devices','2.5');
Insert into plugins values ('mac_ip_filters','Reports any hooked IP filters','2.5');
Insert into plugins values ('mac_keychaindump','Recovers possbile keychain keys. Use chainbreaker to open related keychain files','2.5');
Insert into plugins values ('mac_ldrmodules','Compares the output of proc maps with the list of libraries from libdl','2.5');
Insert into plugins values ('mac_librarydump','Dumps the executable of a process','2.5');
Insert into plugins values ('mac_list_files','Lists files in the file cache','2.5');
Insert into plugins values ('mac_list_kauth_listeners','Lists Kauth Scope listeners','2.5');
Insert into plugins values ('mac_list_kauth_scopes','Lists Kauth Scopes and their status','2.5');
Insert into plugins values ('mac_list_raw','List applications with promiscuous sockets','2.5');
Insert into plugins values ('mac_list_sessions','Enumerates sessions','2.5');
Insert into plugins values ('mac_list_zones','Prints active zones','2.5');
Insert into plugins values ('mac_lsmod','Lists loaded kernel modules','2.5');
Insert into plugins values ('mac_lsmod_iokit','Lists loaded kernel modules through IOkit','2.5');
Insert into plugins values ('mac_lsmod_kext_map','Lists loaded kernel modules','2.5');
Insert into plugins values ('mac_lsof','Lists per-process opened files','2.5');
Insert into plugins values ('mac_machine_info','Prints machine information about the sample','2.5');
Insert into plugins values ('mac_malfind','Looks for suspicious process mappings','2.5');
Insert into plugins values ('mac_memdump','Dump addressable memory pages to a file','2.5');
Insert into plugins values ('mac_moddump','Writes the specified kernel extension to disk','2.5');
Insert into plugins values ('mac_mount','Prints mounted device information','2.5');
Insert into plugins values ('mac_netstat','Lists active per-process network connections','2.5');
Insert into plugins values ('mac_network_conns','Lists network connections from kernel network structures','2.5');
Insert into plugins values ('mac_notesapp','Finds contents of Notes messages','2.5');
Insert into plugins values ('mac_notifiers','Detects rootkits that add hooks into I/O Kit (e.g. LogKext)','2.5');
Insert into plugins values ('mac_orphan_threads',"Lists threads that don't map back to known modules/processes",'2.5');
Insert into plugins values ('mac_pgrp_hash_table','Walks the process group hash table','2.5');
Insert into plugins values ('mac_pid_hash_table','Walks the pid hash table','2.5');
Insert into plugins values ('mac_print_boot_cmdline','Prints kernel boot arguments','2.5');
Insert into plugins values ('mac_proc_maps','Gets memory maps of processes','2.5');
Insert into plugins values ('mac_procdump','Dumps the executable of a process','2.5');
Insert into plugins values ('mac_psaux','Prints processes with arguments in user land (**argv)','2.5');
Insert into plugins values ('mac_psenv','Prints processes with environment in user land (**envp)','2.5');
Insert into plugins values ('mac_pslist','List Running Processes','2.5');
Insert into plugins values ('mac_pstree','Show parent/child relationship of processes','2.5');
Insert into plugins values ('mac_psxview','Find hidden processes with various process listings','2.5');
Insert into plugins values ('mac_recover_filesystem','Recover the cached filesystem','2.5');
Insert into plugins values ('mac_route','Prints the routing table','2.5');
Insert into plugins values ('mac_socket_filters','Reports socket filters','2.5');
Insert into plugins values ('mac_strings','Match physical offsets to virtual addresses (may take a while, VERY verbose)','2.5');
Insert into plugins values ('mac_tasks','List Active Tasks','2.5');
Insert into plugins values ('mac_threads','List Process Threads','2.5');
Insert into plugins values ('mac_threads_simple','Lists threads along with their start time and priority','2.5');
Insert into plugins values ('mac_trustedbsd','Lists malicious trustedbsd policies','2.5');
Insert into plugins values ('mac_version','Prints the Mac version','2.5');
Insert into plugins values ('mac_volshell','Shell in the memory image','2.5');
Insert into plugins values ('mac_yarascan','Scan memory for yara signatures','2.5');
Insert into plugins values ('machoinfo','Dump Mach-O file format information','2.5');
Insert into plugins values ('malfind','Find hidden and injected code','2.5');
Insert into plugins values ('mbrparser','Scans for and parses potential Master Boot Records (MBRs)','2.5');
Insert into plugins values ('memdump','Dump the addressable memory for a process','2.5');
Insert into plugins values ('memmap','Print the memory map','2.5');
Insert into plugins values ('messagehooks','List desktop and thread window message hooks','2.5');
Insert into plugins values ('mftparser','Scans for and parses potential MFT entries','2.5');
Insert into plugins values ('moddump','Dump a kernel driver to an executable file sample','2.5');
Insert into plugins values ('modscan','Pool scanner for kernel modules','2.5');
Insert into plugins values ('modules','Print list of loaded modules','2.5');
Insert into plugins values ('multiscan','Scan for various objects at once','2.5');
Insert into plugins values ('mutantscan','Pool scanner for mutex objects','2.5');
Insert into plugins values ('netscan','Scan a Vista (or later) image for connections and sockets','2.5');
Insert into plugins values ('notepad','List currently displayed notepad text','2.5');
Insert into plugins values ('objtypescan','Scan for Windows object type objects','2.5');
Insert into plugins values ('patcher','Patches memory based on page scans','2.5');
Insert into plugins values ('poolpeek','Configurable pool scanner plugin','2.5');
Insert into plugins values ('pooltracker','Show a summary of pool tag usage','2.5');
Insert into plugins values ('printkey','Print a registry key, and its subkeys and values','2.5');
Insert into plugins values ('privs','Display process privileges','2.5');
Insert into plugins values ('procdump','Dump a process to an executable file sample','2.5');
Insert into plugins values ('pslist','Print all running processes by following the EPROCESS lists','2.5');
Insert into plugins values ('psscan','Pool scanner for process objects','2.5');
Insert into plugins values ('pstree','Print process list as a tree','2.5');
Insert into plugins values ('psxview','Find hidden processes with various process listings','2.5');
Insert into plugins values ('qemuinfo','Dump Qemu information','2.5');
Insert into plugins values ('raw2dmp','Converts a physical memory sample to a windbg crash dump','2.5');
Insert into plugins values ('screenshot','Save a pseudo-screenshot based on GDI windows','2.5');
Insert into plugins values ('servicediff','List Windows services (ala Plugx)','2.5');
Insert into plugins values ('sessions','List details on _MM_SESSION_SPACE (user logon sessions)','2.5');
Insert into plugins values ('shellbags','Prints ShellBags info','2.5');
Insert into plugins values ('shimcache','Parses the Application Compatibility Shim Cache registry key','2.5');
Insert into plugins values ('shutdowntime','Print ShutdownTime of machine from registry','2.5');
Insert into plugins values ('sockets','Print list of open sockets','2.5');
Insert into plugins values ('sockscan','Pool scanner for tcp socket objects','2.5');
Insert into plugins values ('ssdt','Display SSDT entries','2.5');
Insert into plugins values ('strings','Match physical offsets to virtual addresses (may take a while, VERY verbose)','2.5');
Insert into plugins values ('svcscan','Scan for Windows services','2.5');
Insert into plugins values ('symlinkscan','Pool scanner for symlink objects','2.5');
Insert into plugins values ('thrdscan','Pool scanner for thread objects','2.5');
Insert into plugins values ('threads','Investigate _ETHREAD and _KTHREADs','2.5');
Insert into plugins values ('timeliner','Creates a timeline from various artifacts in memory','2.5');
Insert into plugins values ('timers','Print kernel timers and associated module DPCs','2.5');
Insert into plugins values ('truecryptmaster','Recover TrueCrypt 7.1a Master Keys','2.5');
Insert into plugins values ('truecryptpassphrase','TrueCrypt Cached Passphrase Finder','2.5');
Insert into plugins values ('truecryptsummary','TrueCrypt Summary','2.5');
Insert into plugins values ('unloadedmodules','Print list of unloaded modules','2.5');
Insert into plugins values ('userassist','Print userassist registry keys and information','2.5');
Insert into plugins values ('userhandles','Dump the USER handle tables','2.5');
Insert into plugins values ('vaddump','Dumps out the vad sections to a file','2.5');
Insert into plugins values ('vadinfo','Dump the VAD info','2.5');
Insert into plugins values ('vadtree','Walk the VAD tree and display in tree format','2.5');
Insert into plugins values ('vadwalk','Walk the VAD tree','2.5');
Insert into plugins values ('vboxinfo','Dump virtualbox information','2.5');
Insert into plugins values ('verinfo','Prints out the version information from PE images','2.5');
Insert into plugins values ('vmwareinfo','Dump VMware VMSS/VMSN information','2.5');
Insert into plugins values ('volshell','Shell in the memory image','2.5');
Insert into plugins values ('win10cookie','Find the ObHeaderCookie value for Windows 10','2.5');
Insert into plugins values ('windows','Print Desktop Windows (verbose details)','2.5');
Insert into plugins values ('wintree','Print Z-Order Desktop Windows Tree','2.5');
Insert into plugins values ('wndscan','Pool scanner for window stations','2.5');
Insert into plugins values ('yarascan','Scan process or kernel memory with Yara signatures','2.5');

# Profiles for Volatility 2.6 Insert Statements
insert into profiles values ('VistaSP0x64','A Profile for Windows Vista SP0 x64','2.6');
insert into profiles values ('VistaSP0x86','A Profile for Windows Vista SP0 x86','2.6');
insert into profiles values ('VistaSP1x64','A Profile for Windows Vista SP1 x64','2.6');
insert into profiles values ('VistaSP1x86','A Profile for Windows Vista SP1 x86','2.6');
insert into profiles values ('VistaSP2x64','A Profile for Windows Vista SP2 x64','2.6');
insert into profiles values ('VistaSP2x86','A Profile for Windows Vista SP2 x86','2.6');
insert into profiles values ('Win10x64','A Profile for Windows 10 x64','2.6');
insert into profiles values ('Win10x86','A Profile for Windows 10 x86','2.6');
insert into profiles values ('Win10x64_10586','A Profile for Windows 10 x64 (10.0.10586.306 / 2016-04-23)','2.6');
insert into profiles values ('Win10x64_14393','A Profile for Windows 10 x64 (10.0.14393.0 / 2016-07-16)','2.6');
insert into profiles values ('Win10x86_10586','A Profile for Windows 10 x86 (10.0.10586.420 / 2016-05-28)','2.6');
insert into profiles values ('Win10x86_14393','A Profile for Windows 10 x86 (10.0.14393.0 / 2016-07-16)','2.6');
insert into profiles values ('Win2003SP0x86','A Profile for Windows 2003 SP0 x86','2.6');
insert into profiles values ('Win2003SP1x64','A Profile for Windows 2003 SP1 x64','2.6');
insert into profiles values ('Win2003SP1x86','A Profile for Windows 2003 SP1 x86','2.6');
insert into profiles values ('Win2003SP2x64','A Profile for Windows 2003 SP2 x64','2.6');
insert into profiles values ('Win2003SP2x86','A Profile for Windows 2003 SP2 x86','2.6');
insert into profiles values ('Win2008R2SP0x64','A Profile for Windows 2008 R2 SP0 x64','2.6');
insert into profiles values ('Win2008R2SP1x64','A Profile for Windows 2008 R2 SP1 x64','2.6');
insert into profiles values ('Win2008R2SP1x64_23418','A Profile for Windows 2008 R2 SP1 x64 (6.1.7601.23418 / 2016-04-09)','2.6');
insert into profiles values ('Win2008SP1x64','A Profile for Windows 2008 SP1 x64','2.6');
insert into profiles values ('Win2008SP1x86','A Profile for Windows 2008 SP1 x86','2.6');
insert into profiles values ('Win2008SP2x64','A Profile for Windows 2008 SP2 x64','2.6');
insert into profiles values ('Win2008SP2x86','A Profile for Windows 2008 SP2 x86','2.6');
insert into profiles values ('Win2012R2x64','A Profile for Windows Server 2012 R2 x64','2.6');
insert into profiles values ('Win2012R2x64_18340','A Profile for Windows Server 2012 R2 x64 (6.3.9600.18340 / 2016-05-13)','2.6');
insert into profiles values ('Win2012x64','A Profile for Windows Server 2012 x64','2.6');
insert into profiles values ('Win2016x64_14393','A Profile for Windows Server 2016 x64 (10.0.14393.0 / 2016-07-16)','2.6');
insert into profiles values ('Win7SP0x64','A Profile for Windows 7 SP0 x64','2.6');
insert into profiles values ('Win7SP0x86','A Profile for Windows 7 SP0 x86','2.6');
insert into profiles values ('Win7SP1x64','A Profile for Windows 7 SP1 x64','2.6');
insert into profiles values ('Win7SP1x86','A Profile for Windows 7 SP1 x86','2.6');
insert into profiles values ('Win7SP1x64_23418','A Profile for Windows 7 SP1 x64 (6.1.7601.23418 / 2016-04-09)','2.6');
insert into profiles values ('Win7SP1x86_23418','A Profile for Windows 7 SP1 x86 (6.1.7601.23418 / 2016-04-09)','2.6');
insert into profiles values ('Win81U1x64','A Profile for Windows 8.1 Update 1 x64','2.6');
insert into profiles values ('Win81U1x86','A Profile for Windows 8.1 Update 1 x86','2.6');
insert into profiles values ('Win8SP0x64','A Profile for Windows 8 x64','2.6');
insert into profiles values ('Win8SP0x86','A Profile for Windows 8 x86','2.6');
insert into profiles values ('Win8SP1x64','A Profile for Windows 8.1 x64','2.6');
insert into profiles values ('Win8SP1x86','A Profile for Windows 8.1 x86','2.6');
insert into profiles values ('Win8SP1x64_18340','A Profile for Windows 8.1 x64 (6.3.9600.18340 / 2016-05-13)','2.6');
insert into profiles values ('WinXPSP1x64','A Profile for Windows XP SP1 x64','2.6');
insert into profiles values ('WinXPSP2x64','A Profile for Windows XP SP2 x64','2.6');
insert into profiles values ('WinXPSP2x86','A Profile for Windows XP SP2 x86','2.6');
insert into profiles values ('WinXPSP3x86','A Profile for Windows XP SP3 x86','2.6');

# Plugins for Volatility 2.6 Insert Statements
Insert into plugins values ('amcache','Print AmCache information','2.6');
Insert into plugins values ('apihooks','Detect API hooks in process and kernel memory','2.6');
Insert into plugins values ('atoms','Print session and window station atom tables','2.6');
Insert into plugins values ('atomscan','Pool scanner for atom tables','2.6');
Insert into plugins values ('auditpol','Prints out the Audit Policies from HKLM\SECURITY\Policy\PolAdtEv','2.6');
Insert into plugins values ('bigpools','Dump the big page pools using BigPagePoolScanner','2.6');
Insert into plugins values ('bioskbd','Reads the keyboard buffer from Real Mode memory','2.6');
Insert into plugins values ('cachedump','Dumps cached domain hashes from memory','2.6');
Insert into plugins values ('callbacks','Print system-wide notification routines','2.6');
Insert into plugins values ('clipboard','Extract the contents of the windows clipboard','2.6');
Insert into plugins values ('cmdline','Display process command-line arguments','2.6');
Insert into plugins values ('cmdscan','Extract command history by scanning for _COMMAND_HISTORY','2.6');
Insert into plugins values ('connections','Print list of open connections [Windows XP and 2003 Only]','2.6');
Insert into plugins values ('connscan','Pool scanner for tcp connections','2.6');
Insert into plugins values ('consoles','Extract command history by scanning for _CONSOLE_INFORMATION','2.6');
Insert into plugins values ('crashinfo','Dump crash-dump information','2.6');
Insert into plugins values ('deskscan','Poolscaner for tagDESKTOP (desktops)','2.6');
Insert into plugins values ('devicetree','Show device tree','2.6');
Insert into plugins values ('dlldump','Dump DLLs from a process address space','2.6');
Insert into plugins values ('dlllist','Print list of loaded dlls for each process','2.6');
Insert into plugins values ('driverirp','Driver IRP hook detection','2.6');
Insert into plugins values ('drivermodule','Associate driver objects to kernel modules','2.6');
Insert into plugins values ('driverscan','Pool scanner for driver objects','2.6');
Insert into plugins values ('dumpcerts','Dump RSA private and public SSL keys','2.6');
Insert into plugins values ('dumpfiles','Extract memory mapped and cached files','2.6');
Insert into plugins values ('dumpregistry','Dumps registry files out to disk','2.6');
Insert into plugins values ('editbox','Dumps various data from ComCtl Edit controls (experimental: ListBox, ComboBox)','2.6');
Insert into plugins values ('envars','Display process environment variables','2.6');
Insert into plugins values ('eventhooks','Print details on windows event hooks','2.6');
Insert into plugins values ('evtlogs','Extract Windows Event Logs (XP/2003 only)','2.6');
Insert into plugins values ('filescan','Pool scanner for file objects','2.6');
Insert into plugins values ('gahti','Dump the USER handle type information','2.6');
Insert into plugins values ('gditimers','Print installed GDI timers and callbacks','2.6');
Insert into plugins values ('gdt','Display Global Descriptor Table','2.6');
Insert into plugins values ('getservicesids','Get the names of services in the Registry and return Calculated SID','2.6');
Insert into plugins values ('getsids','Print the SIDs owning each process','2.6');
Insert into plugins values ('handles','Print list of open handles for each process','2.6');
Insert into plugins values ('hashdump','Dumps passwords hashes (LM/NTLM) from memory','2.6');
Insert into plugins values ('hibinfo','Dump hibernation file information','2.6');
Insert into plugins values ('hivedump','Prints out a hive','2.6');
Insert into plugins values ('hivelist','Print list of registry hives.','2.6');
Insert into plugins values ('hivescan','Pool scanner for registry hives','2.6');
Insert into plugins values ('hpakextract','Extract physical memory from an HPAK file','2.6');
Insert into plugins values ('hpakinfo','Info on an HPAK file','2.6');
Insert into plugins values ('idt','Display Interrupt Descriptor Table','2.6');
Insert into plugins values ('iehistory','Reconstruct Internet Explorer cache / history','2.6');
Insert into plugins values ('imagecopy','Copies a physical address space out as a raw DD image','2.6');
Insert into plugins values ('imageinfo','Identify information for the image','2.6');
Insert into plugins values ('impscan','Scan for calls to imported functions','2.6');
Insert into plugins values ('joblinks','Print process job link information','2.6');
Insert into plugins values ('kdbgscan','Search for and dump potential KDBG values','2.6');
Insert into plugins values ('kpcrscan','Search for and dump potential KPCR values','2.6');
Insert into plugins values ('ldrmodules','Detect unlinked DLLs','2.6');
Insert into plugins values ('limeinfo','Dump Lime file format information','2.6');
Insert into plugins values ('linux_apihooks','Checks for userland apihooks','2.6');
Insert into plugins values ('linux_arp','Print the ARP table','2.6');
Insert into plugins values ('linux_aslr_shift','Automatically detect the Linux ASLR shift','2.6');
Insert into plugins values ('linux_banner','Prints the Linux banner information','2.6');
Insert into plugins values ('linux_bash','Recover bash history from bash process memory','2.6');
Insert into plugins values ('linux_bash_env',"Recover a process' dynamic environment variables",'2.6');
Insert into plugins values ('linux_bash_hash','Recover bash hash table from bash process memory','2.6');
Insert into plugins values ('linux_check_afinfo','Verifies the operation function pointers of network protocols','2.6');
Insert into plugins values ('linux_check_creds','Checks if any processes are sharing credential structures','2.6');
Insert into plugins values ('linux_check_evt_arm','Checks the Exception Vector Table to look for syscall table hooking','2.6');
Insert into plugins values ('linux_check_fop','Check file operation structures for rootkit modifications','2.6');
Insert into plugins values ('linux_check_idt','Checks if the IDT has been altered','2.6');
Insert into plugins values ('linux_check_inline_kernel','Check for inline kernel hooks','2.6');
Insert into plugins values ('linux_check_modules','Compares module list to sysfs info, if available','2.6');
Insert into plugins values ('linux_check_syscall','Checks if the system call table has been altered','2.6');
Insert into plugins values ('linux_check_syscall_arm','Checks if the system call table has been altered','2.6');
Insert into plugins values ('linux_check_tty','Checks tty devices for hooks','2.6');
Insert into plugins values ('linux_cpuinfo','Prints info about each active processor','2.6');
Insert into plugins values ('linux_dentry_cache','Gather files from the dentry cache','2.6');
Insert into plugins values ('linux_dmesg','Gather dmesg buffer','2.6');
Insert into plugins values ('linux_dump_map','Writes selected memory mappings to disk','2.6');
Insert into plugins values ('linux_dynamic_env ',"Recover a process' dynamic environment variables",'2.6');
Insert into plugins values ('linux_elfs','Find ELF binaries in process mappings','2.6');
Insert into plugins values ('linux_enumerate_files','Lists files referenced by the filesystem cache','2.6');
Insert into plugins values ('linux_find_file','Lists and recovers files from memory','2.6');
Insert into plugins values ('linux_getcwd','Lists current working directory of each process','2.6');
Insert into plugins values ('linux_hidden_modules','Carves memory to find hidden kernel modules','2.6');
Insert into plugins values ('linux_ifconfig','Gathers active interfaces','2.6');
Insert into plugins values ('linux_info_regs',"It's like 'info registers' in GDB. It prints out all the",'2.6');
Insert into plugins values ('linux_iomem','Provides output similar to /proc/iomem','2.6');
Insert into plugins values ('linux_kernel_opened_files','Lists files that are opened from within the kernel','2.6');
Insert into plugins values ('linux_keyboard_notifiers','Parses the keyboard notifier call chain','2.6');
Insert into plugins values ('linux_ldrmodules','Compares the output of proc maps with the list of libraries from libdl','2.6');
Insert into plugins values ('linux_library_list','Lists libraries loaded into a process','2.6');
Insert into plugins values ('linux_librarydump','Dumps shared libraries in process memory to disk','2.6');
Insert into plugins values ('linux_list_raw','List applications with promiscuous sockets','2.6');
Insert into plugins values ('linux_lsmod','Gather loaded kernel modules','2.6');
Insert into plugins values ('linux_lsof','Lists file descriptors and their path','2.6');
Insert into plugins values ('linux_malfind','Looks for suspicious process mappings','2.6');
Insert into plugins values ('linux_memmap','Dumps the memory map for linux tasks','2.6');
Insert into plugins values ('linux_moddump','Extract loaded kernel modules','2.6');
Insert into plugins values ('linux_mount','Gather mounted fs/devices','2.6');
Insert into plugins values ('linux_mount_cache','Gather mounted fs/devices from kmem_cache','2.6');
Insert into plugins values ('linux_netfilter','Lists Netfilter hooks','2.6');
Insert into plugins values ('linux_netscan','Carves for network connection structures','2.6');
Insert into plugins values ('linux_netstat','Lists open sockets','2.6');
Insert into plugins values ('linux_pidhashtable','Enumerates processes through the PID hash table','2.6');
Insert into plugins values ('linux_pkt_queues','Writes per-process packet queues out to disk','2.6');
Insert into plugins values ('linux_plthook',"Scan ELF binaries' PLT for hooks to non-NEEDED images",'2.6');
Insert into plugins values ('linux_proc_maps','Gathers process memory maps','2.6');
Insert into plugins values ('linux_proc_maps_rb','Gathers process maps for linux through the mappings red-black tree','2.6');
Insert into plugins values ('linux_procdump',"Dumps a process's executable image to disk",'2.6');
Insert into plugins values ('linux_process_hollow','Checks for signs of process hollowing','2.6');
Insert into plugins values ('linux_psaux','Gathers processes along with full command line and start time','2.6');
Insert into plugins values ('linux_psenv','Gathers processes along with their static environment variables','2.6');
Insert into plugins values ('linux_pslist','Gather active tasks by walking the task_struct->task list','2.6');
Insert into plugins values ('linux_pslist_cache','Gather tasks from the kmem_cache','2.6');
Insert into plugins values ('linux_psscan','Scan physical memory for processes','2.6');
Insert into plugins values ('linux_pstree','Shows the parent/child relationship between processes','2.6');
Insert into plugins values ('linux_psxview ','Find hidden processes with various process listings','2.6');
Insert into plugins values ('linux_recover_filesystem','Recovers the entire cached file system from memory','2.6');
Insert into plugins values ('linux_route_cache','Recovers the routing cache from memory','2.6');
Insert into plugins values ('linux_sk_buff_cache','Recovers packets from the sk_buff kmem_cache','2.6');
Insert into plugins values ('linux_slabinfo','Mimics /proc/slabinfo on a running machine','2.6');
Insert into plugins values ('linux_strings','Match physical offsets to virtual addresses (may take a while, VERY verbose)','2.6');
Insert into plugins values ('linux_threads','Prints threads of processes','2.6');
Insert into plugins values ('linux_tmpfs','Recovers tmpfs filesystems from memory','2.6');
Insert into plugins values ('linux_truecrypt_passphrase','Recovers cached Truecrypt passphrases','2.6');
Insert into plugins values ('linux_vma_cache','Gather VMAs from the vm_area_struct cache','2.6');
Insert into plugins values ('linux_volshell','Shell in the memory image','2.6');
Insert into plugins values ('linux_yarascan','A shell in the Linux memory image','2.6');
Insert into plugins values ('lsadump','Dump (decrypted) LSA secrets from the registry','2.6');
Insert into plugins values ('mac_adium','Lists Adium messages','2.6');
Insert into plugins values ('mac_apihooks','Checks for API hooks in processes','2.6');
Insert into plugins values ('mac_apihooks_kernel','Checks to see if system call and kernel functions are hooked','2.6');
Insert into plugins values ('mac_arp','Prints the arp table','2.6');
Insert into plugins values ('mac_bash','Recover bash history from bash process memory','2.6');
Insert into plugins values ('mac_bash_env',"Recover bash's environment variables",'2.6');
Insert into plugins values ('mac_bash_hash','Recover bash hash table from bash process memory','2.6');
Insert into plugins values ('mac_calendar','Gets calendar events from Calendar.app','2.6');
Insert into plugins values ('mac_check_fop','Validate File Operation Pointers','2.6');
Insert into plugins values ('mac_check_mig_table',"Lists entires in the kernel's MIG table",'2.6');
Insert into plugins values ('mac_check_syscall_shadow','Looks for shadow system call tables','2.6');
Insert into plugins values ('mac_check_syscalls','Checks to see if system call table entries are hooked','2.6');
Insert into plugins values ('mac_check_sysctl','Checks for unknown sysctl handlers','2.6');
Insert into plugins values ('mac_check_trap_table','Checks to see if mach trap table entries are hooked','2.6');
Insert into plugins values ('mac_compressed_swap','Prints Mac OS X VM compressor stats and dumps all compressed pages','2.6');
Insert into plugins values ('mac_contacts','Gets contact names from Contacts.app','2.6');
Insert into plugins values ('mac_dead_procs','Prints terminated/de-allocated processes','2.6');
Insert into plugins values ('mac_dead_sockets','Prints terminated/de-allocated network sockets','2.6');
Insert into plugins values ('mac_dead_vnodes','Lists freed vnode structures','2.6');
Insert into plugins values ('mac_devfs','Lists files in the file cache','2.6');
Insert into plugins values ('mac_dmesg','Prints the kernel debug buffer','2.6');
Insert into plugins values ('mac_dump_file','Dumps a specified file','2.6');
Insert into plugins values ('mac_dump_maps','Dumps memory ranges of process(es), optionally including pages in compressed swap','2.6');
Insert into plugins values ('mac_dyld_maps','Gets memory maps of processes from dyld data structures','2.6');
Insert into plugins values ('mac_find_aslr_shift','Find the ASLR shift value for 10.8+ images','2.6');
Insert into plugins values ('mac_get_profile','Automatically detect Mac profiles','2.6');
Insert into plugins values ('mac_ifconfig','Lists network interface information for all devices','2.6');
Insert into plugins values ('mac_interest_handlers','Lists IOKit Interest Handlers','2.6');
Insert into plugins values ('mac_ip_filters','Reports any hooked IP filters','2.6');
Insert into plugins values ('mac_kernel_classes','Lists loaded c++ classes in the kernel','2.6');
Insert into plugins values ('mac_kevents','Show parent/child relationship of processes','2.6');
Insert into plugins values ('mac_keychaindump','Recovers possbile keychain keys. Use chainbreaker to open related keychain files','2.6');
Insert into plugins values ('mac_ldrmodules','Compares the output of proc maps with the list of libraries from libdl','2.6');
Insert into plugins values ('mac_librarydump','Dumps the executable of a process','2.6');
Insert into plugins values ('mac_list_files','Lists files in the file cache','2.6');
Insert into plugins values ('mac_list_kauth_listeners','Lists Kauth Scope listeners','2.6');
Insert into plugins values ('mac_list_kauth_scopes','Lists Kauth Scopes and their status','2.6');
Insert into plugins values ('mac_list_raw','List applications with promiscuous sockets','2.6');
Insert into plugins values ('mac_list_sessions','Enumerates sessions','2.6');
Insert into plugins values ('mac_list_zones','Prints active zones','2.6');
Insert into plugins values ('mac_lsmod','Lists loaded kernel modules','2.6');
Insert into plugins values ('mac_lsmod_iokit','Lists loaded kernel modules through IOkit','2.6');
Insert into plugins values ('mac_lsmod_kext_map','Lists loaded kernel modules','2.6');
Insert into plugins values ('mac_lsof','Lists per-process opened files','2.6');
Insert into plugins values ('mac_machine_info','Prints machine information about the sample','2.6');
Insert into plugins values ('mac_malfind','Looks for suspicious process mappings','2.6');
Insert into plugins values ('mac_memdump','Dump addressable memory pages to a file','2.6');
Insert into plugins values ('mac_moddump','Writes the specified kernel extension to disk','2.6');
Insert into plugins values ('mac_mount','Prints mounted device information','2.6');
Insert into plugins values ('mac_netstat','Lists active per-process network connections','2.6');
Insert into plugins values ('mac_network_conns','Lists network connections from kernel network structures','2.6');
Insert into plugins values ('mac_notesapp','Finds contents of Notes messages','2.6');
Insert into plugins values ('mac_notifiers','Detects rootkits that add hooks into I/O Kit (e.g. LogKext)','2.6');
Insert into plugins values ('mac_orphan_threads',"Lists threads that don't map back to known modules/processes",'2.6');
Insert into plugins values ('mac_pgrp_hash_table','Walks the process group hash table','2.6');
Insert into plugins values ('mac_pid_hash_table','Walks the pid hash table','2.6');
Insert into plugins values ('mac_print_boot_cmdline','Prints kernel boot arguments','2.6');
Insert into plugins values ('mac_proc_maps','Gets memory maps of processes','2.6');
Insert into plugins values ('mac_procdump','Dumps the executable of a process','2.6');
Insert into plugins values ('mac_psaux','Prints processes with arguments in user land (**argv)','2.6');
Insert into plugins values ('mac_psenv','Prints processes with environment in user land (**envp)','2.6');
Insert into plugins values ('mac_pslist','List Running Processes','2.6');
Insert into plugins values ('mac_pstree','Show parent/child relationship of processes','2.6');
Insert into plugins values ('mac_psxview','Find hidden processes with various process listings','2.6');
Insert into plugins values ('mac_recover_filesystem','Recover the cached filesystem','2.6');
Insert into plugins values ('mac_route','Prints the routing table','2.6');
Insert into plugins values ('mac_socket_filters','Reports socket filters','2.6');
Insert into plugins values ('mac_strings','Match physical offsets to virtual addresses (may take a while, VERY verbose)','2.6');
Insert into plugins values ('mac_tasks','List Active Tasks','2.6');
Insert into plugins values ('mac_threads','List Process Threads','2.6');
Insert into plugins values ('mac_threads_simple','Lists threads along with their start time and priority','2.6');
Insert into plugins values ('mac_timers','Reports timers set by kernel drivers','2.6');
Insert into plugins values ('mac_trustedbsd','Lists malicious trustedbsd policies','2.6');
Insert into plugins values ('mac_version','Prints the Mac version','2.6');
Insert into plugins values ('mac_vfsevents','Lists processes filtering file system events','2.6');
Insert into plugins values ('mac_volshell','Shell in the memory image','2.6');
Insert into plugins values ('mac_yarascan','Scan memory for yara signatures','2.6');
Insert into plugins values ('machoinfo','Dump Mach-O file format information','2.6');
Insert into plugins values ('malfind','Find hidden and injected code','2.6');
Insert into plugins values ('mbrparser','Scans for and parses potential Master Boot Records (MBRs)','2.6');
Insert into plugins values ('memdump','Dump the addressable memory for a process','2.6');
Insert into plugins values ('memmap','Print the memory map','2.6');
Insert into plugins values ('messagehooks','List desktop and thread window message hooks','2.6');
Insert into plugins values ('mftparser','Scans for and parses potential MFT entries','2.6');
Insert into plugins values ('moddump','Dump a kernel driver to an executable file sample','2.6');
Insert into plugins values ('modscan','Pool scanner for kernel modules','2.6');
Insert into plugins values ('modules','Print list of loaded modules','2.6');
Insert into plugins values ('multiscan','Scan for various objects at once','2.6');
Insert into plugins values ('mutantscan','Pool scanner for mutex objects','2.6');
Insert into plugins values ('netscan','Scan a Vista (or later) image for connections and sockets','2.6');
Insert into plugins values ('notepad','List currently displayed notepad text','2.6');
Insert into plugins values ('objtypescan','Scan for Windows object type objects','2.6');
Insert into plugins values ('patcher','Patches memory based on page scans','2.6');
Insert into plugins values ('poolpeek','Configurable pool scanner plugin','2.6');
Insert into plugins values ('pooltracker','Show a summary of pool tag usage','2.6');
Insert into plugins values ('printkey','Print a registry key, and its subkeys and values','2.6');
Insert into plugins values ('privs','Display process privileges','2.6');
Insert into plugins values ('procdump','Dump a process to an executable file sample','2.6');
Insert into plugins values ('pslist','Print all running processes by following the EPROCESS lists','2.6');
Insert into plugins values ('psscan','Pool scanner for process objects','2.6');
Insert into plugins values ('pstree','Print process list as a tree','2.6');
Insert into plugins values ('psxview','Find hidden processes with various process listings','2.6');
Insert into plugins values ('qemuinfo','Dump Qemu information','2.6');
Insert into plugins values ('raw2dmp','Converts a physical memory sample to a windbg crash dump','2.6');
Insert into plugins values ('screenshot','Save a pseudo-screenshot based on GDI windows','2.6');
Insert into plugins values ('servicediff','List Windows services (ala Plugx)','2.6');
Insert into plugins values ('sessions','List details on _MM_SESSION_SPACE (user logon sessions)','2.6');
Insert into plugins values ('shellbags','Prints ShellBags info','2.6');
Insert into plugins values ('shimcache','Parses the Application Compatibility Shim Cache registry key','2.6');
Insert into plugins values ('shutdowntime','Print ShutdownTime of machine from registry','2.6');
Insert into plugins values ('sockets','Print list of open sockets','2.6');
Insert into plugins values ('sockscan','Pool scanner for tcp socket objects','2.6');
Insert into plugins values ('ssdt','Display SSDT entries','2.6');
Insert into plugins values ('strings','Match physical offsets to virtual addresses (may take a while, VERY verbose)','2.6');
Insert into plugins values ('svcscan','Scan for Windows services','2.6');
Insert into plugins values ('symlinkscan','Pool scanner for symlink objects','2.6');
Insert into plugins values ('thrdscan','Pool scanner for thread objects','2.6');
Insert into plugins values ('threads','Investigate _ETHREAD and _KTHREADs','2.6');
Insert into plugins values ('timeliner','Creates a timeline from various artifacts in memory','2.6');
Insert into plugins values ('timers','Print kernel timers and associated module DPCs','2.6');
Insert into plugins values ('truecryptmaster','Recover TrueCrypt 7.1a Master Keys','2.6');
Insert into plugins values ('truecryptpassphrase','TrueCrypt Cached Passphrase Finder','2.6');
Insert into plugins values ('truecryptsummary','TrueCrypt Summary','2.6');
Insert into plugins values ('unloadedmodules','Print list of unloaded modules','2.6');
Insert into plugins values ('userassist','Print userassist registry keys and information','2.6');
Insert into plugins values ('userhandles','Dump the USER handle tables','2.6');
Insert into plugins values ('vaddump','Dumps out the vad sections to a file','2.6');
Insert into plugins values ('vadinfo','Dump the VAD info','2.6');
Insert into plugins values ('vadtree','Walk the VAD tree and display in tree format','2.6');
Insert into plugins values ('vadwalk','Walk the VAD tree','2.6');
Insert into plugins values ('vboxinfo','Dump virtualbox information','2.6');
Insert into plugins values ('verinfo','Prints out the version information from PE images','2.6');
Insert into plugins values ('vmwareinfo','Dump VMware VMSS/VMSN information','2.6');
Insert into plugins values ('volshell','Shell in the memory image','2.6');
Insert into plugins values ('win10cookie','Find the ObHeaderCookie value for Windows 10','2.6');
Insert into plugins values ('windows','Print Desktop Windows (verbose details)','2.6');
Insert into plugins values ('wintree','Print Z-Order Desktop Windows Tree','2.6');
Insert into plugins values ('wndscan','Pool scanner for window stations','2.6');
Insert into plugins values ('yarascan','Scan process or kernel memory with Yara signatures','2.6');
